# Generated by Django 2.0.9 on 2018-11-25 06:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='notes',
            field=models.TextField(blank=True, help_text='Tell us anything we should know when delivering your order.', verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='In case we need to call you about your order', max_length=128, verbose_name='Phone number'),
        ),
    ]
