# Generated by Django 2.0.9 on 2018-12-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_billingaddress_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatuschange',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderStatusChange',
        ),
    ]
